Controllers/StockController.cs
using Microsoft.AspNetCore.Mvc;
using StockListRazor_1._2.Model;
using System.Linq;

namespace StockListRazor_1._2.Controllers
{
    [Route("api/Stock")]
    [ApiController]
    public class StockController : Controller
    {
        private readonly ApplicationDbContext _db;

        public StockController(ApplicationDbContext db)
        {
            _db = db;   
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data= _db.Stock.ToList() });                  //this api call should return the book list
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StockListRazor_1._2.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StockListRazor_1._2.Pages
{
    public class IndexModel : PageModel                     /* inherits index model*/
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StockListRazor_1._2.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/StockList/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StockListRazor_1._2.Model;
using System.Threading.Tasks;

namespace StockListRazor_1._2.Pages.StockList
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public CreateModel(ApplicationDbContext db)
        {
            _db= db;
        }

        [BindProperty]
        public Stock Stock { get; set; }                //passes the empty stock automatically, dont need to do it seperately

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)                             //server side validation
            {
                await _db.Stock.AddAsync(Stock);                //adds stock to que
                await _db.SaveChangesAsync();                   //when this is executed, data is pushed to database
                return RedirectToPage("Index");                                 
            }
            else
            {
                return Page();
            }
        }
    }
}

Pages/StockList/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StockListRazor_1._2.Model;
using System.Threading.Tasks;

namespace StockListRazor_1._2.Pages.StockList
{
    public class EditModel : PageModel
    {
        private ApplicationDbContext _db;

        public EditModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Stock Stock { get; set; }
        public object StockFromDb { get; private set; }

        public async Task OnGet(int id)
        {
            Stock = await _db.Stock.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var StockFromDb = await _db.Stock.FindAsync(Stock.Id);
                StockFromDb.Ticker = Stock.Ticker;
                StockFromDb.Price = Stock.Price;
                StockFromDb.Ammount = Stock.Ammount;

                await _db.SaveChangesAsync();

                return RedirectToPage("Index");               //fix redirect
            }
            return RedirectToPage();
        }
    }
}

Pages/StockList/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StockListRazor_1._2.Model;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace StockListRazor_1._2.Pages.StockList
{
    public class IndexModel : PageModel
    {

        private readonly ApplicationDbContext _db;


        public IndexModel(ApplicationDbContext db)              //using dependancy injection
        {
            _db = db;                                           //can pull from container and inject into page
        }

        public IEnumerable<Stock> Stocks { get; set; }


        public async Task OnGet()       
        {
            Stocks = await _db.Stock.ToListAsync();
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            var stock = await _db.Stock.FindAsync(id);
            if(stock == null)
            {
                return NotFound();
            }
            _db.Stock.Remove(stock);
            await _db.SaveChangesAsync();

            return RedirectToPage("Index");   

        }
               
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Andreas</h1>
    <p>This is your very creative and styalized home page</p>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockListRazor_1._2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">StockListRazor_1._2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/StockList/Index">Stock</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - StockListRazor_1._2 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Pages/StockList/Create.cshtml
@page
@model StockListRazor_1._2.Pages.StockList.CreateModel
<br />
<h2 class="text-info">Add New Stock</h2>
<br />

<div class="border container" style="padding:30px;">
	<form method="post">
		<div class="text-danger" asp-validation-summary="ModelOnly"></div>
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Stock.Ticker"></label>							@*Adding Ticker symbol*@
			</div>
			<div class="col-6">
				<input asp-for="Stock.Ticker" class="form-control" />
			</div>
			<span asp-validation-for="Stock.Ticker" class="text-danger"></span>
		</div>


		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Stock.Price"></label>							@*Adding Ticker Price*@
			</div>
			<div class="col-6">
				<input asp-for="Stock.Price" class="form-control" />
			</div>
			<span asp-validation-for="Stock.Price" class="text-danger"></span>
		</div>


		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Stock.Ammount"></label>							@*Adding how many were bought, Post handler will push to database*@
			</div>
			<div class="col-6">
				<input asp-for="Stock.Ammount" class="form-control" />
			</div>
			<span asp-validation-for="Stock.Ammount" class="text-danger"></span>
		</div>


		<div class="form-group row">
			<div class="col-3 offset-3">
				<input type="submit" value="Create" class="btn btn-primary form-control" />
			</div>
			<div class="col-3">
				<a asp-page="Index" class="btn btn-success form-control">Back to List</a>
			</div>
		</div>
	</form>
</div>

@section Scripts{
<partial name="_ValidationScriptsPartial" />			@*Client side validation*@
}

Pages/StockList/Edit.cshtml
@page
@model StockListRazor_1._2.Pages.StockList.EditModel


<br />
<h2 class="text-info">Edit Stock</h2>
<br />

<div class="border container" style="padding:30px;">
	<form method="post">
		<input type="hidden" asp-for="Stock.Id" />
		<div class="text-danger" asp-validation-summary="ModelOnly"></div>

		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Stock.Ticker"></label>
			</div>
			<div class="col-6">
				<input asp-for="Stock.Ticker" class="form-control" />
			</div>
			<span asp-validation-for="Stock.Ticker" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Stock.Price"></label>
			</div>
			<div class="col-6">
				<input asp-for="Stock.Price" class="form-control" />
			</div>
			<span asp-validation-for="Stock.Price" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Stock.Ammount"></label>
			</div>
			<div class="col-6">
				<input asp-for="Stock.Ammount" class="form-control" />
			</div>
			<span asp-validation-for="Stock.Ammount" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3 offset-3">
				<input type="submit" value="Update" class="btn btn-primary form-control" />
			</div>
			<div class="col-3">
				<a asp-page="Index" class="btn btn-success form-control">Back to List</a>
			</div>
		</div>
	</form>
</div>

@section Scripts{
<partial name="_ValidationScriptsPartial" />
}

Pages/StockList/Index.cshtml
@page
@model StockListRazor_1._2.Pages.StockList.IndexModel

<br />
<div class="container row p-0 m-0">
    <div class="col-9">
        <h2 class="text-info">Stock List</h2>
    </div>
    <div class="col-3">
        <a asp-page="Create" class="btn btn-info form-control text-white">Add New Stock</a>
    </div>


    <div class="col-12 border p-3 mt-3">
        <form method="post">
            @if (Model.Stocks.Count() > 0)
            {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            <label asp-for="Stocks.FirstOrDefault().Ticker"></label>
                        </th>
                        <th>
                            @*@Html.DisplayNameFor(m=>m.Books.FirstOrDefault().Author)*@
                            <label asp-for="Stocks.FirstOrDefault().Price"></label>
                        </th>
                        <th>
                            <label asp-for="Stocks.FirstOrDefault().Ammount"></label>
                        </th>
                        <th>

                        </th>
                    </tr>
                    @foreach (var item in Model.Stocks)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.Ticker)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Price)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Ammount)
                            </td>
                            <td>
                                <button asp-page-handler="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to delete?')" class="btn btn-danger btn-sm">Delete</button>
                                <a asp-page="Edit" asp-route-id="@item.Id" class="btn btn-success btn-sm text-white">Edit</a>
                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>No books available.</p>
            }
        </form>
    </div>


</div>

<div class="col-12" style="text-align:center">
        <br />
        <span class="h3 text-info">OR</span>
        <br /><br />
    </div>
    <div class="col-12 border p-3">

        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Ticker</th>
                    <th> Price</th>
                    <th> Ammount</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>

@section Scripts{ 
    <script src="~/js/stockList.js"></script>
}